// Generated by gencpp from file auv_msgs_stamped/mx28_stamped.msg
// DO NOT EDIT!


#ifndef AUV_MSGS_STAMPED_MESSAGE_MX28_STAMPED_H
#define AUV_MSGS_STAMPED_MESSAGE_MX28_STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auv_msgs_stamped
{
template <class ContainerAllocator>
struct mx28_stamped_
{
  typedef mx28_stamped_<ContainerAllocator> Type;

  mx28_stamped_()
    : position(0.0)
    , speed(0.0)
    , load(0.0)
    , voltage(0.0)
    , temperature(0.0)  {
    }
  mx28_stamped_(const ContainerAllocator& _alloc)
    : position(0.0)
    , speed(0.0)
    , load(0.0)
    , voltage(0.0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef float _position_type;
  _position_type position;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _load_type;
  _load_type load;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> const> ConstPtr;

}; // struct mx28_stamped_

typedef ::auv_msgs_stamped::mx28_stamped_<std::allocator<void> > mx28_stamped;

typedef boost::shared_ptr< ::auv_msgs_stamped::mx28_stamped > mx28_stampedPtr;
typedef boost::shared_ptr< ::auv_msgs_stamped::mx28_stamped const> mx28_stampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator1> & lhs, const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.speed == rhs.speed &&
    lhs.load == rhs.load &&
    lhs.voltage == rhs.voltage &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator1> & lhs, const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auv_msgs_stamped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48ece77b2d029663968108978cdfd7c1";
  }

  static const char* value(const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48ece77b2d029663ULL;
  static const uint64_t static_value2 = 0x968108978cdfd7c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_msgs_stamped/mx28_stamped";
  }

  static const char* value(const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position\n"
"float32 speed\n"
"float32 load\n"
"float32 voltage\n"
"float32 temperature\n"
;
  }

  static const char* value(const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.speed);
      stream.next(m.load);
      stream.next(m.voltage);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mx28_stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_msgs_stamped::mx28_stamped_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "load: ";
    Printer<float>::stream(s, indent + "  ", v.load);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MSGS_STAMPED_MESSAGE_MX28_STAMPED_H
