(cl:defpackage auv_msgs_stamped-msg
  (:use )
  (:export
   "<ALTIMETER_STAMPED>"
   "ALTIMETER_STAMPED"
   "<ANTI_ROLLING_STAMPED>"
   "ANTI_ROLLING_STAMPED"
   "<BMS_STAMPED>"
   "BMS_STAMPED"
   "<BOARD_ARM1_STAMPED>"
   "BOARD_ARM1_STAMPED"
   "<BOARD_ARM2_STAMPED>"
   "BOARD_ARM2_STAMPED"
   "<GPS_DVL_INS_STAMPED>"
   "GPS_DVL_INS_STAMPED"
   "<JOYSTICK_STAMPED>"
   "JOYSTICK_STAMPED"
   "<KELLER_PA3_STAMPED>"
   "KELLER_PA3_STAMPED"
   "<LIMIT_SWITCH_STAMPED>"
   "LIMIT_SWITCH_STAMPED"
   "<MOTOR_STAMPED>"
   "MOTOR_STAMPED"
   "<MX28_STAMPED>"
   "MX28_STAMPED"
  ))

