# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from auv_msgs_stamped/bms_stamped.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class bms_stamped(genpy.Message):
  _md5sum = "3439bc04eebf35f1a5ae09dd8a711f94"
  _type = "auv_msgs_stamped/bms_stamped"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 batteryTotal
float32 batteryCapacity
float32 batteryUsed
float32 batteryPercentage
float32 batteryCurrent
float32 baterryVoltage
"""
  __slots__ = ['batteryTotal','batteryCapacity','batteryUsed','batteryPercentage','batteryCurrent','baterryVoltage']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       batteryTotal,batteryCapacity,batteryUsed,batteryPercentage,batteryCurrent,baterryVoltage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bms_stamped, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.batteryTotal is None:
        self.batteryTotal = 0.
      if self.batteryCapacity is None:
        self.batteryCapacity = 0.
      if self.batteryUsed is None:
        self.batteryUsed = 0.
      if self.batteryPercentage is None:
        self.batteryPercentage = 0.
      if self.batteryCurrent is None:
        self.batteryCurrent = 0.
      if self.baterryVoltage is None:
        self.baterryVoltage = 0.
    else:
      self.batteryTotal = 0.
      self.batteryCapacity = 0.
      self.batteryUsed = 0.
      self.batteryPercentage = 0.
      self.batteryCurrent = 0.
      self.baterryVoltage = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.batteryTotal, _x.batteryCapacity, _x.batteryUsed, _x.batteryPercentage, _x.batteryCurrent, _x.baterryVoltage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.batteryTotal, _x.batteryCapacity, _x.batteryUsed, _x.batteryPercentage, _x.batteryCurrent, _x.baterryVoltage,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.batteryTotal, _x.batteryCapacity, _x.batteryUsed, _x.batteryPercentage, _x.batteryCurrent, _x.baterryVoltage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.batteryTotal, _x.batteryCapacity, _x.batteryUsed, _x.batteryPercentage, _x.batteryCurrent, _x.baterryVoltage,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
