(cl:in-package utils-msg)
(cl:export '(HEADER-VAL
          HEADER
          SAMPLE_COUNT-VAL
          SAMPLE_COUNT
          EKF_ROLL-VAL
          EKF_ROLL
          EKF_PITCH-VAL
          EKF_PITCH
          EKF_YAW-VAL
          EKF_YAW
          EKF_LAT-VAL
          EKF_LAT
          EKF_LON-VAL
          EKF_LON
          EKF_ALT-VAL
          EKF_ALT
          EKF_VN-VAL
          EKF_VN
          EKF_VE-VAL
          EKF_VE
          EKF_VD-VAL
          EKF_VD
          EKF_VX-VAL
          EKF_VX
          EKF_VY-VAL
          EKF_VY
          EKF_VZ-VAL
          EKF_VZ
          RAD_GYRO_X-VAL
          RAD_GYRO_X
          RAD_GYRO_Y-VAL
          RAD_GYRO_Y
          RAD_GYRO_Z-VAL
          RAD_GYRO_Z
          ANGULAR_ACC_X-VAL
          ANGULAR_ACC_X
          ANGULAR_ACC_Y-VAL
          ANGULAR_ACC_Y
          ANGULAR_ACC_Z-VAL
          ANGULAR_ACC_Z
          ALT_DVL-VAL
          ALT_DVL
          DVL_ERROR_CODE-VAL
          DVL_ERROR_CODE
          FLAG_TO_CHECK-VAL
          FLAG_TO_CHECK
          IMU_DEG_GYRO_X-VAL
          IMU_DEG_GYRO_X
          IMU_DEG_GYRO_Y-VAL
          IMU_DEG_GYRO_Y
          IMU_DEG_GYRO_Z-VAL
          IMU_DEG_GYRO_Z
          IMU_MAG_X-VAL
          IMU_MAG_X
          IMU_MAG_Y-VAL
          IMU_MAG_Y
          IMU_MAG_Z-VAL
          IMU_MAG_Z
          IMU_ACC_X-VAL
          IMU_ACC_X
          IMU_ACC_Y-VAL
          IMU_ACC_Y
          IMU_ACC_Z-VAL
          IMU_ACC_Z
          GPS_LAT-VAL
          GPS_LAT
          GPS_LON-VAL
          GPS_LON
          GPS_ALT-VAL
          GPS_ALT
          GPS_VN-VAL
          GPS_VN
          GPS_VE-VAL
          GPS_VE
          GPS_VD-VAL
          GPS_VD
          DVL_VX-VAL
          DVL_VX
          DVL_VY-VAL
          DVL_VY
          DVL_VZ-VAL
          DVL_VZ
))