# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from utils/board_arm2_stamped.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import utils.msg

class board_arm2_stamped(genpy.Message):
  _md5sum = "521c67addccb2fe148b0af42a4f47323"
  _type = "utils/board_arm2_stamped"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
mx28_stamped mx28_status
bms_stamped bms_status
keller_pa3_stamped pressure_status
anti_rolling_stamped roll_motor_status

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: utils/mx28_stamped
float32 position
float32 speed
float32 load
float32 voltage
float32 temperature

================================================================================
MSG: utils/bms_stamped
float32 batteryTotal
float32 batteryCapacity
float32 batteryUsed
float32 batteryPercentage
float32 batteryCurrent
float32 baterryVoltage

================================================================================
MSG: utils/keller_pa3_stamped
float32 pressure
float32 temperature

================================================================================
MSG: utils/anti_rolling_stamped
float32 kp
float32 ki
float32 kd
float32 angle
"""
  __slots__ = ['header','mx28_status','bms_status','pressure_status','roll_motor_status']
  _slot_types = ['std_msgs/Header','utils/mx28_stamped','utils/bms_stamped','utils/keller_pa3_stamped','utils/anti_rolling_stamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,mx28_status,bms_status,pressure_status,roll_motor_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(board_arm2_stamped, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mx28_status is None:
        self.mx28_status = utils.msg.mx28_stamped()
      if self.bms_status is None:
        self.bms_status = utils.msg.bms_stamped()
      if self.pressure_status is None:
        self.pressure_status = utils.msg.keller_pa3_stamped()
      if self.roll_motor_status is None:
        self.roll_motor_status = utils.msg.anti_rolling_stamped()
    else:
      self.header = std_msgs.msg.Header()
      self.mx28_status = utils.msg.mx28_stamped()
      self.bms_status = utils.msg.bms_stamped()
      self.pressure_status = utils.msg.keller_pa3_stamped()
      self.roll_motor_status = utils.msg.anti_rolling_stamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_17f().pack(_x.mx28_status.position, _x.mx28_status.speed, _x.mx28_status.load, _x.mx28_status.voltage, _x.mx28_status.temperature, _x.bms_status.batteryTotal, _x.bms_status.batteryCapacity, _x.bms_status.batteryUsed, _x.bms_status.batteryPercentage, _x.bms_status.batteryCurrent, _x.bms_status.baterryVoltage, _x.pressure_status.pressure, _x.pressure_status.temperature, _x.roll_motor_status.kp, _x.roll_motor_status.ki, _x.roll_motor_status.kd, _x.roll_motor_status.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mx28_status is None:
        self.mx28_status = utils.msg.mx28_stamped()
      if self.bms_status is None:
        self.bms_status = utils.msg.bms_stamped()
      if self.pressure_status is None:
        self.pressure_status = utils.msg.keller_pa3_stamped()
      if self.roll_motor_status is None:
        self.roll_motor_status = utils.msg.anti_rolling_stamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.mx28_status.position, _x.mx28_status.speed, _x.mx28_status.load, _x.mx28_status.voltage, _x.mx28_status.temperature, _x.bms_status.batteryTotal, _x.bms_status.batteryCapacity, _x.bms_status.batteryUsed, _x.bms_status.batteryPercentage, _x.bms_status.batteryCurrent, _x.bms_status.baterryVoltage, _x.pressure_status.pressure, _x.pressure_status.temperature, _x.roll_motor_status.kp, _x.roll_motor_status.ki, _x.roll_motor_status.kd, _x.roll_motor_status.angle,) = _get_struct_17f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_17f().pack(_x.mx28_status.position, _x.mx28_status.speed, _x.mx28_status.load, _x.mx28_status.voltage, _x.mx28_status.temperature, _x.bms_status.batteryTotal, _x.bms_status.batteryCapacity, _x.bms_status.batteryUsed, _x.bms_status.batteryPercentage, _x.bms_status.batteryCurrent, _x.bms_status.baterryVoltage, _x.pressure_status.pressure, _x.pressure_status.temperature, _x.roll_motor_status.kp, _x.roll_motor_status.ki, _x.roll_motor_status.kd, _x.roll_motor_status.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mx28_status is None:
        self.mx28_status = utils.msg.mx28_stamped()
      if self.bms_status is None:
        self.bms_status = utils.msg.bms_stamped()
      if self.pressure_status is None:
        self.pressure_status = utils.msg.keller_pa3_stamped()
      if self.roll_motor_status is None:
        self.roll_motor_status = utils.msg.anti_rolling_stamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.mx28_status.position, _x.mx28_status.speed, _x.mx28_status.load, _x.mx28_status.voltage, _x.mx28_status.temperature, _x.bms_status.batteryTotal, _x.bms_status.batteryCapacity, _x.bms_status.batteryUsed, _x.bms_status.batteryPercentage, _x.bms_status.batteryCurrent, _x.bms_status.baterryVoltage, _x.pressure_status.pressure, _x.pressure_status.temperature, _x.roll_motor_status.kp, _x.roll_motor_status.ki, _x.roll_motor_status.kd, _x.roll_motor_status.angle,) = _get_struct_17f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_17f = None
def _get_struct_17f():
    global _struct_17f
    if _struct_17f is None:
        _struct_17f = struct.Struct("<17f")
    return _struct_17f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
