// Generated by gencpp from file utils/anti_rolling_stamped.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_ANTI_ROLLING_STAMPED_H
#define UTILS_MESSAGE_ANTI_ROLLING_STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct anti_rolling_stamped_
{
  typedef anti_rolling_stamped_<ContainerAllocator> Type;

  anti_rolling_stamped_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , angle(0.0)  {
    }
  anti_rolling_stamped_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _kp_type;
  _kp_type kp;

   typedef float _ki_type;
  _ki_type ki;

   typedef float _kd_type;
  _kd_type kd;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::utils::anti_rolling_stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::anti_rolling_stamped_<ContainerAllocator> const> ConstPtr;

}; // struct anti_rolling_stamped_

typedef ::utils::anti_rolling_stamped_<std::allocator<void> > anti_rolling_stamped;

typedef boost::shared_ptr< ::utils::anti_rolling_stamped > anti_rolling_stampedPtr;
typedef boost::shared_ptr< ::utils::anti_rolling_stamped const> anti_rolling_stampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::anti_rolling_stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::anti_rolling_stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::anti_rolling_stamped_<ContainerAllocator1> & lhs, const ::utils::anti_rolling_stamped_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::anti_rolling_stamped_<ContainerAllocator1> & lhs, const ::utils::anti_rolling_stamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::anti_rolling_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::anti_rolling_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::anti_rolling_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::anti_rolling_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::anti_rolling_stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::anti_rolling_stamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::anti_rolling_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2811c74f32419e9c2ba6ba9376f51a5b";
  }

  static const char* value(const ::utils::anti_rolling_stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2811c74f32419e9cULL;
  static const uint64_t static_value2 = 0x2ba6ba9376f51a5bULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::anti_rolling_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/anti_rolling_stamped";
  }

  static const char* value(const ::utils::anti_rolling_stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::anti_rolling_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 kp\n"
"float32 ki\n"
"float32 kd\n"
"float32 angle\n"
;
  }

  static const char* value(const ::utils::anti_rolling_stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::anti_rolling_stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct anti_rolling_stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::anti_rolling_stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::anti_rolling_stamped_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<float>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<float>::stream(s, indent + "  ", v.kd);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_ANTI_ROLLING_STAMPED_H
