// Generated by gencpp from file utils/ColorRGBAStamped.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_COLORRGBASTAMPED_H
#define UTILS_MESSAGE_COLORRGBASTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct ColorRGBAStamped_
{
  typedef ColorRGBAStamped_<ContainerAllocator> Type;

  ColorRGBAStamped_()
    : header()
    , r(0.0)
    , g(0.0)
    , b(0.0)
    , a(0.0)  {
    }
  ColorRGBAStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , r(0.0)
    , g(0.0)
    , b(0.0)
    , a(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _r_type;
  _r_type r;

   typedef float _g_type;
  _g_type g;

   typedef float _b_type;
  _b_type b;

   typedef float _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::utils::ColorRGBAStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::ColorRGBAStamped_<ContainerAllocator> const> ConstPtr;

}; // struct ColorRGBAStamped_

typedef ::utils::ColorRGBAStamped_<std::allocator<void> > ColorRGBAStamped;

typedef boost::shared_ptr< ::utils::ColorRGBAStamped > ColorRGBAStampedPtr;
typedef boost::shared_ptr< ::utils::ColorRGBAStamped const> ColorRGBAStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::ColorRGBAStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::ColorRGBAStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::ColorRGBAStamped_<ContainerAllocator1> & lhs, const ::utils::ColorRGBAStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::ColorRGBAStamped_<ContainerAllocator1> & lhs, const ::utils::ColorRGBAStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::ColorRGBAStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::ColorRGBAStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::ColorRGBAStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::ColorRGBAStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::ColorRGBAStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::ColorRGBAStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::ColorRGBAStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "970ecd4722ca3bc9c59a06e7d6a0f73a";
  }

  static const char* value(const ::utils::ColorRGBAStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x970ecd4722ca3bc9ULL;
  static const uint64_t static_value2 = 0xc59a06e7d6a0f73aULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::ColorRGBAStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/ColorRGBAStamped";
  }

  static const char* value(const ::utils::ColorRGBAStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::ColorRGBAStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::ColorRGBAStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::ColorRGBAStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorRGBAStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::ColorRGBAStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::ColorRGBAStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<float>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_COLORRGBASTAMPED_H
