// Generated by gencpp from file utils/CommandLongResponse.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_COMMANDLONGRESPONSE_H
#define UTILS_MESSAGE_COMMANDLONGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct CommandLongResponse_
{
  typedef CommandLongResponse_<ContainerAllocator> Type;

  CommandLongResponse_()
    : success(false)
    , result(0)  {
    }
  CommandLongResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::utils::CommandLongResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::CommandLongResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandLongResponse_

typedef ::utils::CommandLongResponse_<std::allocator<void> > CommandLongResponse;

typedef boost::shared_ptr< ::utils::CommandLongResponse > CommandLongResponsePtr;
typedef boost::shared_ptr< ::utils::CommandLongResponse const> CommandLongResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::CommandLongResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::CommandLongResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::CommandLongResponse_<ContainerAllocator1> & lhs, const ::utils::CommandLongResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::CommandLongResponse_<ContainerAllocator1> & lhs, const ::utils::CommandLongResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::CommandLongResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::CommandLongResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::CommandLongResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::CommandLongResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::CommandLongResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::CommandLongResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::CommandLongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cd894375e4e3d2861d2222772894fdb";
  }

  static const char* value(const ::utils::CommandLongResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cd894375e4e3d28ULL;
  static const uint64_t static_value2 = 0x61d2222772894fdbULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::CommandLongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/CommandLongResponse";
  }

  static const char* value(const ::utils::CommandLongResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::CommandLongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"# raw result returned by COMMAND_ACK\n"
"uint8 result\n"
"\n"
;
  }

  static const char* value(const ::utils::CommandLongResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::CommandLongResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandLongResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::CommandLongResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::CommandLongResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_COMMANDLONGRESPONSE_H
