// Generated by gencpp from file utils/CommandInt.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_COMMANDINT_H
#define UTILS_MESSAGE_COMMANDINT_H

#include <ros/service_traits.h>


#include <utils/CommandIntRequest.h>
#include <utils/CommandIntResponse.h>


namespace utils
{

struct CommandInt
{

typedef CommandIntRequest Request;
typedef CommandIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandInt
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::CommandInt > {
  static const char* value()
  {
    return "5d5fd287bf3d27ad6ec508b1692f3b09";
  }

  static const char* value(const ::utils::CommandInt&) { return value(); }
};

template<>
struct DataType< ::utils::CommandInt > {
  static const char* value()
  {
    return "utils/CommandInt";
  }

  static const char* value(const ::utils::CommandInt&) { return value(); }
};


// service_traits::MD5Sum< ::utils::CommandIntRequest> should match
// service_traits::MD5Sum< ::utils::CommandInt >
template<>
struct MD5Sum< ::utils::CommandIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::CommandInt >::value();
  }
  static const char* value(const ::utils::CommandIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::CommandIntRequest> should match
// service_traits::DataType< ::utils::CommandInt >
template<>
struct DataType< ::utils::CommandIntRequest>
{
  static const char* value()
  {
    return DataType< ::utils::CommandInt >::value();
  }
  static const char* value(const ::utils::CommandIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::CommandIntResponse> should match
// service_traits::MD5Sum< ::utils::CommandInt >
template<>
struct MD5Sum< ::utils::CommandIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::CommandInt >::value();
  }
  static const char* value(const ::utils::CommandIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::CommandIntResponse> should match
// service_traits::DataType< ::utils::CommandInt >
template<>
struct DataType< ::utils::CommandIntResponse>
{
  static const char* value()
  {
    return DataType< ::utils::CommandInt >::value();
  }
  static const char* value(const ::utils::CommandIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_COMMANDINT_H
