// Generated by gencpp from file utils/Error.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_ERROR_H
#define UTILS_MESSAGE_ERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct Error_
{
  typedef Error_<ContainerAllocator> Type;

  Error_()
    : header()
    , along_track(0.0)
    , cross_track(0.0)  {
    }
  Error_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , along_track(0.0)
    , cross_track(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _along_track_type;
  _along_track_type along_track;

   typedef double _cross_track_type;
  _cross_track_type cross_track;





  typedef boost::shared_ptr< ::utils::Error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::Error_<ContainerAllocator> const> ConstPtr;

}; // struct Error_

typedef ::utils::Error_<std::allocator<void> > Error;

typedef boost::shared_ptr< ::utils::Error > ErrorPtr;
typedef boost::shared_ptr< ::utils::Error const> ErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::Error_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::Error_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::Error_<ContainerAllocator1> & lhs, const ::utils::Error_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.along_track == rhs.along_track &&
    lhs.cross_track == rhs.cross_track;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::Error_<ContainerAllocator1> & lhs, const ::utils::Error_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::Error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::Error_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Error_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6e8e9b3c251df9be04fce0859ad0cd8";
  }

  static const char* value(const ::utils::Error_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6e8e9b3c251df9bULL;
  static const uint64_t static_value2 = 0xe04fce0859ad0cd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/Error";
  }

  static const char* value(const ::utils::Error_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 along_track\n"
"float64 cross_track\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::Error_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::Error_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.along_track);
      stream.next(m.cross_track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Error_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::Error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::Error_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "along_track: ";
    Printer<double>::stream(s, indent + "  ", v.along_track);
    s << indent << "cross_track: ";
    Printer<double>::stream(s, indent + "  ", v.cross_track);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_ERROR_H
