// Generated by gencpp from file utils/keller_pa3_stamped.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_KELLER_PA3_STAMPED_H
#define UTILS_MESSAGE_KELLER_PA3_STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct keller_pa3_stamped_
{
  typedef keller_pa3_stamped_<ContainerAllocator> Type;

  keller_pa3_stamped_()
    : pressure(0.0)
    , temperature(0.0)  {
    }
  keller_pa3_stamped_(const ContainerAllocator& _alloc)
    : pressure(0.0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef float _pressure_type;
  _pressure_type pressure;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::utils::keller_pa3_stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::keller_pa3_stamped_<ContainerAllocator> const> ConstPtr;

}; // struct keller_pa3_stamped_

typedef ::utils::keller_pa3_stamped_<std::allocator<void> > keller_pa3_stamped;

typedef boost::shared_ptr< ::utils::keller_pa3_stamped > keller_pa3_stampedPtr;
typedef boost::shared_ptr< ::utils::keller_pa3_stamped const> keller_pa3_stampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::keller_pa3_stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::keller_pa3_stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::keller_pa3_stamped_<ContainerAllocator1> & lhs, const ::utils::keller_pa3_stamped_<ContainerAllocator2> & rhs)
{
  return lhs.pressure == rhs.pressure &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::keller_pa3_stamped_<ContainerAllocator1> & lhs, const ::utils::keller_pa3_stamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::keller_pa3_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::keller_pa3_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::keller_pa3_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::keller_pa3_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::keller_pa3_stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::keller_pa3_stamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::keller_pa3_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62167d413640523c7acac52cadc6c243";
  }

  static const char* value(const ::utils::keller_pa3_stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62167d413640523cULL;
  static const uint64_t static_value2 = 0x7acac52cadc6c243ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::keller_pa3_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/keller_pa3_stamped";
  }

  static const char* value(const ::utils::keller_pa3_stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::keller_pa3_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pressure\n"
"float32 temperature\n"
;
  }

  static const char* value(const ::utils::keller_pa3_stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::keller_pa3_stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pressure);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct keller_pa3_stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::keller_pa3_stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::keller_pa3_stamped_<ContainerAllocator>& v)
  {
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_KELLER_PA3_STAMPED_H
