// Generated by gencpp from file utils/KeyboardCommand.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_KEYBOARDCOMMAND_H
#define UTILS_MESSAGE_KEYBOARDCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct KeyboardCommand_
{
  typedef KeyboardCommand_<ContainerAllocator> Type;

  KeyboardCommand_()
    : header()
    , mode(0)
    , forward_pwm(0.0)
    , side_pwm(0.0)  {
    }
  KeyboardCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)
    , forward_pwm(0.0)
    , side_pwm(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef double _forward_pwm_type;
  _forward_pwm_type forward_pwm;

   typedef double _side_pwm_type;
  _side_pwm_type side_pwm;





  typedef boost::shared_ptr< ::utils::KeyboardCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::KeyboardCommand_<ContainerAllocator> const> ConstPtr;

}; // struct KeyboardCommand_

typedef ::utils::KeyboardCommand_<std::allocator<void> > KeyboardCommand;

typedef boost::shared_ptr< ::utils::KeyboardCommand > KeyboardCommandPtr;
typedef boost::shared_ptr< ::utils::KeyboardCommand const> KeyboardCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::KeyboardCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::KeyboardCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::KeyboardCommand_<ContainerAllocator1> & lhs, const ::utils::KeyboardCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode == rhs.mode &&
    lhs.forward_pwm == rhs.forward_pwm &&
    lhs.side_pwm == rhs.side_pwm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::KeyboardCommand_<ContainerAllocator1> & lhs, const ::utils::KeyboardCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::KeyboardCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::KeyboardCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::KeyboardCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::KeyboardCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::KeyboardCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::KeyboardCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::KeyboardCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9aa3434eb1fadadc277fed694bf3b36";
  }

  static const char* value(const ::utils::KeyboardCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9aa3434eb1fadadULL;
  static const uint64_t static_value2 = 0xc277fed694bf3b36ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::KeyboardCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/KeyboardCommand";
  }

  static const char* value(const ::utils::KeyboardCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::KeyboardCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8 mode\n"
"\n"
"float64 forward_pwm\n"
"float64 side_pwm\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::KeyboardCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::KeyboardCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
      stream.next(m.forward_pwm);
      stream.next(m.side_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyboardCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::KeyboardCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::KeyboardCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "forward_pwm: ";
    Printer<double>::stream(s, indent + "  ", v.forward_pwm);
    s << indent << "side_pwm: ";
    Printer<double>::stream(s, indent + "  ", v.side_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_KEYBOARDCOMMAND_H
