// Generated by gencpp from file utils/motor_stamped.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_MOTOR_STAMPED_H
#define UTILS_MESSAGE_MOTOR_STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct motor_stamped_
{
  typedef motor_stamped_<ContainerAllocator> Type;

  motor_stamped_()
    : position(0.0)
    , motor_duty(0.0)
    , motor_temp_on_chip(0.0)
    , motor_temp_ambient(0.0)
    , motor_current(0.0)
    , motor_rspeed(0.0)
    , motor_dspeed(0.0)  {
    }
  motor_stamped_(const ContainerAllocator& _alloc)
    : position(0.0)
    , motor_duty(0.0)
    , motor_temp_on_chip(0.0)
    , motor_temp_ambient(0.0)
    , motor_current(0.0)
    , motor_rspeed(0.0)
    , motor_dspeed(0.0)  {
  (void)_alloc;
    }



   typedef float _position_type;
  _position_type position;

   typedef float _motor_duty_type;
  _motor_duty_type motor_duty;

   typedef float _motor_temp_on_chip_type;
  _motor_temp_on_chip_type motor_temp_on_chip;

   typedef float _motor_temp_ambient_type;
  _motor_temp_ambient_type motor_temp_ambient;

   typedef float _motor_current_type;
  _motor_current_type motor_current;

   typedef float _motor_rspeed_type;
  _motor_rspeed_type motor_rspeed;

   typedef float _motor_dspeed_type;
  _motor_dspeed_type motor_dspeed;





  typedef boost::shared_ptr< ::utils::motor_stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::motor_stamped_<ContainerAllocator> const> ConstPtr;

}; // struct motor_stamped_

typedef ::utils::motor_stamped_<std::allocator<void> > motor_stamped;

typedef boost::shared_ptr< ::utils::motor_stamped > motor_stampedPtr;
typedef boost::shared_ptr< ::utils::motor_stamped const> motor_stampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::motor_stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::motor_stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::motor_stamped_<ContainerAllocator1> & lhs, const ::utils::motor_stamped_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.motor_duty == rhs.motor_duty &&
    lhs.motor_temp_on_chip == rhs.motor_temp_on_chip &&
    lhs.motor_temp_ambient == rhs.motor_temp_ambient &&
    lhs.motor_current == rhs.motor_current &&
    lhs.motor_rspeed == rhs.motor_rspeed &&
    lhs.motor_dspeed == rhs.motor_dspeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::motor_stamped_<ContainerAllocator1> & lhs, const ::utils::motor_stamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::motor_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::motor_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::motor_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::motor_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::motor_stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::motor_stamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::motor_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09905cb75dcdfe375d3e51249c09d663";
  }

  static const char* value(const ::utils::motor_stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09905cb75dcdfe37ULL;
  static const uint64_t static_value2 = 0x5d3e51249c09d663ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::motor_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/motor_stamped";
  }

  static const char* value(const ::utils::motor_stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::motor_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position\n"
"float32 motor_duty\n"
"float32 motor_temp_on_chip\n"
"float32 motor_temp_ambient\n"
"float32 motor_current\n"
"float32 motor_rspeed\n"
"float32 motor_dspeed\n"
;
  }

  static const char* value(const ::utils::motor_stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::motor_stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.motor_duty);
      stream.next(m.motor_temp_on_chip);
      stream.next(m.motor_temp_ambient);
      stream.next(m.motor_current);
      stream.next(m.motor_rspeed);
      stream.next(m.motor_dspeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::motor_stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::motor_stamped_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "motor_duty: ";
    Printer<float>::stream(s, indent + "  ", v.motor_duty);
    s << indent << "motor_temp_on_chip: ";
    Printer<float>::stream(s, indent + "  ", v.motor_temp_on_chip);
    s << indent << "motor_temp_ambient: ";
    Printer<float>::stream(s, indent + "  ", v.motor_temp_ambient);
    s << indent << "motor_current: ";
    Printer<float>::stream(s, indent + "  ", v.motor_current);
    s << indent << "motor_rspeed: ";
    Printer<float>::stream(s, indent + "  ", v.motor_rspeed);
    s << indent << "motor_dspeed: ";
    Printer<float>::stream(s, indent + "  ", v.motor_dspeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_MOTOR_STAMPED_H
