// Generated by gencpp from file utils/ParamGet.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_PARAMGET_H
#define UTILS_MESSAGE_PARAMGET_H

#include <ros/service_traits.h>


#include <utils/ParamGetRequest.h>
#include <utils/ParamGetResponse.h>


namespace utils
{

struct ParamGet
{

typedef ParamGetRequest Request;
typedef ParamGetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamGet
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::ParamGet > {
  static const char* value()
  {
    return "777d24d2a7ab1765ef009a69f464d2bc";
  }

  static const char* value(const ::utils::ParamGet&) { return value(); }
};

template<>
struct DataType< ::utils::ParamGet > {
  static const char* value()
  {
    return "utils/ParamGet";
  }

  static const char* value(const ::utils::ParamGet&) { return value(); }
};


// service_traits::MD5Sum< ::utils::ParamGetRequest> should match
// service_traits::MD5Sum< ::utils::ParamGet >
template<>
struct MD5Sum< ::utils::ParamGetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::ParamGet >::value();
  }
  static const char* value(const ::utils::ParamGetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::ParamGetRequest> should match
// service_traits::DataType< ::utils::ParamGet >
template<>
struct DataType< ::utils::ParamGetRequest>
{
  static const char* value()
  {
    return DataType< ::utils::ParamGet >::value();
  }
  static const char* value(const ::utils::ParamGetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::ParamGetResponse> should match
// service_traits::MD5Sum< ::utils::ParamGet >
template<>
struct MD5Sum< ::utils::ParamGetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::ParamGet >::value();
  }
  static const char* value(const ::utils::ParamGetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::ParamGetResponse> should match
// service_traits::DataType< ::utils::ParamGet >
template<>
struct DataType< ::utils::ParamGetResponse>
{
  static const char* value()
  {
    return DataType< ::utils::ParamGet >::value();
  }
  static const char* value(const ::utils::ParamGetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_PARAMGET_H
