// Generated by gencpp from file utils/ParamSetResponse.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_PARAMSETRESPONSE_H
#define UTILS_MESSAGE_PARAMSETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <utils/ParamValue.h>

namespace utils
{
template <class ContainerAllocator>
struct ParamSetResponse_
{
  typedef ParamSetResponse_<ContainerAllocator> Type;

  ParamSetResponse_()
    : success(false)
    , value()  {
    }
  ParamSetResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::utils::ParamValue_<ContainerAllocator>  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::utils::ParamSetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::ParamSetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ParamSetResponse_

typedef ::utils::ParamSetResponse_<std::allocator<void> > ParamSetResponse;

typedef boost::shared_ptr< ::utils::ParamSetResponse > ParamSetResponsePtr;
typedef boost::shared_ptr< ::utils::ParamSetResponse const> ParamSetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::ParamSetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::ParamSetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::ParamSetResponse_<ContainerAllocator1> & lhs, const ::utils::ParamSetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::ParamSetResponse_<ContainerAllocator1> & lhs, const ::utils::ParamSetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::ParamSetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::ParamSetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::ParamSetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::ParamSetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::ParamSetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::ParamSetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::ParamSetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "790d22b22b9dbf32a8e8d55578e25477";
  }

  static const char* value(const ::utils::ParamSetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x790d22b22b9dbf32ULL;
  static const uint64_t static_value2 = 0xa8e8d55578e25477ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::ParamSetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/ParamSetResponse";
  }

  static const char* value(const ::utils::ParamSetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::ParamSetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"utils/ParamValue value\n"
"\n"
"\n"
"================================================================================\n"
"MSG: utils/ParamValue\n"
"# Parameter value storage type.\n"
"#\n"
"# Integer and float fields:\n"
"#\n"
"# if integer != 0: it is integer value\n"
"# else if real != 0.0: it is float value\n"
"# else: it is zero.\n"
"\n"
"int64 integer\n"
"float64 real\n"
;
  }

  static const char* value(const ::utils::ParamSetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::ParamSetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParamSetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::ParamSetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::ParamSetResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "value: ";
    s << std::endl;
    Printer< ::utils::ParamValue_<ContainerAllocator> >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_PARAMSETRESPONSE_H
