// Generated by gencpp from file utils/ParamValue.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_PARAMVALUE_H
#define UTILS_MESSAGE_PARAMVALUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct ParamValue_
{
  typedef ParamValue_<ContainerAllocator> Type;

  ParamValue_()
    : integer(0)
    , real(0.0)  {
    }
  ParamValue_(const ContainerAllocator& _alloc)
    : integer(0)
    , real(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _integer_type;
  _integer_type integer;

   typedef double _real_type;
  _real_type real;





  typedef boost::shared_ptr< ::utils::ParamValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::ParamValue_<ContainerAllocator> const> ConstPtr;

}; // struct ParamValue_

typedef ::utils::ParamValue_<std::allocator<void> > ParamValue;

typedef boost::shared_ptr< ::utils::ParamValue > ParamValuePtr;
typedef boost::shared_ptr< ::utils::ParamValue const> ParamValueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::ParamValue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::ParamValue_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::ParamValue_<ContainerAllocator1> & lhs, const ::utils::ParamValue_<ContainerAllocator2> & rhs)
{
  return lhs.integer == rhs.integer &&
    lhs.real == rhs.real;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::ParamValue_<ContainerAllocator1> & lhs, const ::utils::ParamValue_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::ParamValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::ParamValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::ParamValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::ParamValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::ParamValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::ParamValue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::ParamValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2cb1c7a0f6ef0c62d450cd9362c980d";
  }

  static const char* value(const ::utils::ParamValue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2cb1c7a0f6ef0c6ULL;
  static const uint64_t static_value2 = 0x2d450cd9362c980dULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::ParamValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/ParamValue";
  }

  static const char* value(const ::utils::ParamValue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::ParamValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Parameter value storage type.\n"
"#\n"
"# Integer and float fields:\n"
"#\n"
"# if integer != 0: it is integer value\n"
"# else if real != 0.0: it is float value\n"
"# else: it is zero.\n"
"\n"
"int64 integer\n"
"float64 real\n"
;
  }

  static const char* value(const ::utils::ParamValue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::ParamValue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.integer);
      stream.next(m.real);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParamValue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::ParamValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::ParamValue_<ContainerAllocator>& v)
  {
    s << indent << "integer: ";
    Printer<int64_t>::stream(s, indent + "  ", v.integer);
    s << indent << "real: ";
    Printer<double>::stream(s, indent + "  ", v.real);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_PARAMVALUE_H
