// Generated by gencpp from file utils/SetModeResponse.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_SETMODERESPONSE_H
#define UTILS_MESSAGE_SETMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct SetModeResponse_
{
  typedef SetModeResponse_<ContainerAllocator> Type;

  SetModeResponse_()
    : mode_sent(false)  {
    }
  SetModeResponse_(const ContainerAllocator& _alloc)
    : mode_sent(false)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_sent_type;
  _mode_sent_type mode_sent;





  typedef boost::shared_ptr< ::utils::SetModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::SetModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetModeResponse_

typedef ::utils::SetModeResponse_<std::allocator<void> > SetModeResponse;

typedef boost::shared_ptr< ::utils::SetModeResponse > SetModeResponsePtr;
typedef boost::shared_ptr< ::utils::SetModeResponse const> SetModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::SetModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::SetModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::SetModeResponse_<ContainerAllocator1> & lhs, const ::utils::SetModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.mode_sent == rhs.mode_sent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::SetModeResponse_<ContainerAllocator1> & lhs, const ::utils::SetModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::SetModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::SetModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::SetModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::SetModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::SetModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::SetModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::SetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a70bfe6329ecf8f8d858daa6f3db7655";
  }

  static const char* value(const ::utils::SetModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa70bfe6329ecf8f8ULL;
  static const uint64_t static_value2 = 0xd858daa6f3db7655ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::SetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/SetModeResponse";
  }

  static const char* value(const ::utils::SetModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::SetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool mode_sent		# Mode known/parsed correctly and SET_MODE are sent\n"
"\n"
;
  }

  static const char* value(const ::utils::SetModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::SetModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode_sent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::SetModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::SetModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "mode_sent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode_sent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_SETMODERESPONSE_H
