// Generated by gencpp from file utils/SetMode.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_SETMODE_H
#define UTILS_MESSAGE_SETMODE_H

#include <ros/service_traits.h>


#include <utils/SetModeRequest.h>
#include <utils/SetModeResponse.h>


namespace utils
{

struct SetMode
{

typedef SetModeRequest Request;
typedef SetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMode
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::SetMode > {
  static const char* value()
  {
    return "e4f18fa93379f9ff1780d270ce110203";
  }

  static const char* value(const ::utils::SetMode&) { return value(); }
};

template<>
struct DataType< ::utils::SetMode > {
  static const char* value()
  {
    return "utils/SetMode";
  }

  static const char* value(const ::utils::SetMode&) { return value(); }
};


// service_traits::MD5Sum< ::utils::SetModeRequest> should match
// service_traits::MD5Sum< ::utils::SetMode >
template<>
struct MD5Sum< ::utils::SetModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::SetMode >::value();
  }
  static const char* value(const ::utils::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::SetModeRequest> should match
// service_traits::DataType< ::utils::SetMode >
template<>
struct DataType< ::utils::SetModeRequest>
{
  static const char* value()
  {
    return DataType< ::utils::SetMode >::value();
  }
  static const char* value(const ::utils::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::SetModeResponse> should match
// service_traits::MD5Sum< ::utils::SetMode >
template<>
struct MD5Sum< ::utils::SetModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::SetMode >::value();
  }
  static const char* value(const ::utils::SetModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::SetModeResponse> should match
// service_traits::DataType< ::utils::SetMode >
template<>
struct DataType< ::utils::SetModeResponse>
{
  static const char* value()
  {
    return DataType< ::utils::SetMode >::value();
  }
  static const char* value(const ::utils::SetModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_SETMODE_H
