// Generated by gencpp from file utils/ThrustCommand.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_THRUSTCOMMAND_H
#define UTILS_MESSAGE_THRUSTCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct ThrustCommand_
{
  typedef ThrustCommand_<ContainerAllocator> Type;

  ThrustCommand_()
    : header()
    , speed(0.0)  {
    }
  ThrustCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::utils::ThrustCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::ThrustCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ThrustCommand_

typedef ::utils::ThrustCommand_<std::allocator<void> > ThrustCommand;

typedef boost::shared_ptr< ::utils::ThrustCommand > ThrustCommandPtr;
typedef boost::shared_ptr< ::utils::ThrustCommand const> ThrustCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::ThrustCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::ThrustCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::ThrustCommand_<ContainerAllocator1> & lhs, const ::utils::ThrustCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::ThrustCommand_<ContainerAllocator1> & lhs, const ::utils::ThrustCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::ThrustCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::ThrustCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::ThrustCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::ThrustCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::ThrustCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::ThrustCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17b1dfb61067b5181d2fbfcebd547b10";
  }

  static const char* value(const ::utils::ThrustCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17b1dfb61067b518ULL;
  static const uint64_t static_value2 = 0x1d2fbfcebd547b10ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/ThrustCommand";
  }

  static const char* value(const ::utils::ThrustCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 speed\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::ThrustCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::ThrustCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrustCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::ThrustCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::ThrustCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_THRUSTCOMMAND_H
